[project]
name = "research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fca-utils",
    "geg-metrics>=0.2.2",
    "grandiso>=2.2.0",
    "gudhi>=3.12.0",
    "numpy>=2.4.3",
    "odis-python>=2026.4.0",
    "requests>=2.34.2",
    "shapely>=2.1.2",
    "texsoup>=0.3.3",
]

[tool.uv.sources]
fca-utils = { git = "https://github.com/marcelnoehre/fca-utils.git" }
