COUNTRIES = {
    'AL': 'Albania',
    'AD': 'Andorra',
    'AM': 'Armenia',
    'AU': 'Australia',
    'AT': 'Austria',
    'AZ': 'Azerbaijan',
    'BY': 'Belarus',
    'BE': 'Belgium',
    'BA': 'Bosnia and Herzegovina',
    'BG': 'Bulgaria',
    'HR': 'Croatia',
    'CY': 'Cyprus',
    'CZ': 'Czechia',
    'DK': 'Denmark',
    'EE': 'Estonia',
    'FI': 'Finland',
    'FR': 'France',
    'GE': 'Georgia',
    'DE': 'Germany',
    'GR': 'Greece',
    'HU': 'Hungary',
    'IS': 'Iceland',
    'IE': 'Ireland',
    'IL': 'Israel',
    'IT': 'Italy',
    'KZ': 'Kazakhstan',
    'LV': 'Latvia',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'MT': 'Malta',
    'MD': 'Moldova',
    'MC': 'Monaco',
    'ME': 'Montenegro',
    'MA': 'Morocco',
    'NL': 'Netherlands',
    'MK': 'North Macedonia',
    'NO': 'Norway',
    'PL': 'Poland',
    'PT': 'Portugal',
    'RO': 'Romania',
    'RU': 'Russia',
    'SM': 'San Marino',
    'RS': 'Serbia',
    'CS': 'Serbia and Montenegro',
    'SK': 'Slovakia',
    'SI': 'Slovenia',
    'ES': 'Spain',
    'SE': 'Sweden',
    'CH': 'Switzerland',
    'TR': 'Turkey',
    'UA': 'Ukraine',
    'GB': 'United Kingdom',
    'GB-WLS': 'Wales',
    'YU': 'Yugoslavia'
}

CLUSTERS = {
    'Nordic':                  ['IS', 'NO', 'SE', 'DK', 'FI'],
    'British Isles':           ['GB', 'GB-WLS', 'IE'],
    'Benelux':                 ['BE', 'NL', 'LU'],
    'DACH':                    ['DE', 'AT', 'CH'],
    'Iberia':                  ['PT', 'ES', 'AD'],
    'Italian Peninsula':       ['IT', 'SM', 'MC'],
    'Balkans':                 ['AL', 'BA', 'BG', 'HR', 'ME', 'MK', 'RO', 'RS', 'SI'],
    'Visegrad':                ['PL', 'CZ', 'SK', 'HU'],
    'Baltics':                 ['EE', 'LV', 'LT'],
    'Eastern Europe':          ['RU', 'BY', 'UA', 'MD'],
    'Caucasus':                ['GE', 'AM', 'AZ'],
    'Eastern Mediterranean':   ['GR', 'CY', 'TR', 'IL', 'MT'],
    'Non-European':            ['MA', 'KZ', 'AU'],
    'Defunct':                 ['YU', 'CS'],
}